kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      containers:
        - name: my-java-springboot
          image: quay.io/redhat-user-workloads/atul-fulambarkar-tenant/sample-springapp-tssc/sample-springapp-tssc:build-51a95-1691503370
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: java-springboot-app
      
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:  
  name: my-java-springboot-svc
spec:  
  port: 
    targetPort: 8081
  to:  
    kind: Service  
    name: my-java-springboot-svc
